Feature/packer (#26)
* added submission model.

* changes in submission controller.

* Feature/sns (#23)

* added submission model.

* changes in submission controller.

* added sns client.

* added logger in submsn controller

* changes in sbmsn controller

* changes in sbmsn controller.

* updated workflow.

---------

Co-authored-by: Rajas Telang <rajastelang@Rajass-MacBook-Air.local>

diff --git a/.github/workflows/mergepkr.yml b/.github/workflows/mergepkr.yml
--- a/.github/workflows/mergepkr.yml
+++ b/.github/workflows/mergepkr.yml
@@ -44,3 +44,31 @@ jobs:
 
       - name: Deploy Packer
         run: packer build ./packer/aws-debian.pkr.hcl
+
+      - name: Modify Launch Template version with latest AMI
+        run: |
+          echo "::set-output name=ami_id::$(aws ec2 describe-images --filters 'Name=name,Values=csye6225*' --query 'Images[0].ImageId' --output text)"
+     
+      - name: Configure DEMO AWS credentials
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-access-key-id: ${{ secrets.DEMO_AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.DEMO_AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+
+      - name: Creating Launch Template Version
+        run: |
+          aws ec2 create-launch-template-version --launch-template-name ${{ secrets.LAUNCH_TEMPLATE }} --source-version 1 --launch-template-data '{"ImageId":"${{ steps.ami.outputs.ami_id }}"}'
+      
+      - name: Refresh autoscaling group
+        run: |
+          aws autoscaling start-instance-refresh --auto-scaling-group-name ${{ secrets.AUTOSCALING_GROUP }}
+          status=""
+          while [[ $status != "Successful" && $status != "Failed" ]]; do
+            status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name ${{ secrets.AUTOSCALING_GROUP }} --query 'InstanceRefreshes[0].Status' --output text)
+          done
+          echo "Instance refresh status: $status"
+          if [ $status == "Failed" ]; then
+            echo "Instance refresh failed. Exiting with an error."
+            exit 1
+          fi
